### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead

### ISSUE THREAD

**Issue by ddugovic** [2014mchidamb/AdversarialChess#1]
After doing `python process_data.py` using `../Data/GM2001.pgn` the next step in the README.md fails:

```
$ ls ../Data/
-rw-r--r-- 1 lila lila    49530521 Feb 26 08:34 GM2001.pgn
-rw-rw-r-- 1 lila lila 11946358296 Feb 28 00:51 training_data.hdf5
-rw-rw-r-- 1 lila lila   134512600 Feb 28 00:57 player_data.hdf5
-rw-rw-r-- 1 lila lila   452653274 Feb 28 00:59 full_boards.pkl

$ uname -a
Linux dugovic-host 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ python train_model.py 
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "train_model.py", line 14, in <module>
    magikarp = Magikarp(config, sess)
  File "/home/lila/AdversarialChess/model.py", line 18, in __init__
    self.p_data = h5py.File(config['p_datafile'], 'r')
  File "/home/lila/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/lila/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-4rPeHA-build/h5py/h5f.c:1930)
IOError: Unable to open file (Unable to open file: name = '../data/tal_data.hdf5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)
```

**Comment by ddugovic** [comment]
After (on Linux) replacing all `Data` with `data` and replacing `tal_data` with `player_data`, now I observe:

```
$ python train_model.py 
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "train_model.py", line 15, in <module>
    magikarp.train()
  File "/home/lila/AdversarialChess/model.py", line 215, in train
    self.create_model()
  File "/home/lila/AdversarialChess/model.py", line 197, in create_model
    self.create_dis_model()
  File "/home/lila/AdversarialChess/model.py", line 187, in create_dis_model
    self.d_pred_real = self.d_predict(tf.concat(1, [self.person_board_1, self.person_board_2]), self.p_keep)
  File "/home/lila/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1047, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/lila/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/home/lila/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/lila/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/lila/.local/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 165, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/lila/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 367, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/home/lila/.local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
```

**Comment by 2014mchidamb** [comment]
You may need to build TensorFlow from source, as suggested here: https://github.com/tensorflow/tensorflow/issues/7693.

**Comment by ddugovic** [comment]
Thanks, I will attempt to install tensorflow version 0.12.1.

**Comment by ddugovic** [comment]
Thanks, I was using the wrong version and using TensorFlow version 0.12.1 fixes my issue.

**Comment by johndpope** [comment]
fix here - https://github.com/2014mchidamb/AdversarialChess/issues/4
