### ISSUE TITLE
'Game' object has no attribute 'is_end'

### ISSUE THREAD

**Issue by johndpope** [2014mchidamb/AdversarialChess#2]
Hi,

I was planning to open a PR with updated instructions for conda.

I believe I've successfully installed everything - but I can't get 
**python process_data.py** to run.

[Event "FICS rated standard game"]
[Site "FICS freechess.org"]
[Date "2017.01.31"]
[Round "?"]
[White "aberleider"]
[Black "rewqfdsa"]
[Result "1-0"]
[FICSGamesDBGameNo "410988594"]
[WhiteElo "2138"]
[BlackElo "1925"]
[WhiteRD "57.9"]
[BlackRD "34.8"]
[TimeControl "2700+15"]
[Time "22:37:00"]
[WhiteClock "0:45:00.000"]
[BlackClock "0:45:00.000"]
[ECO "D01"]
[PlyCount "79"]

1. d4 d5 2. Nc3 Nf6 3. Bg5 Nbd7 4. Qd3 h6 5. Bh4 g5 6. Bg3 a6 7. O-O-O Bg7 8. h4 g4 9. e4 dxe4 10. Nxe4 Nxe4 11. Qxe4 Nf6 12. Qe5 c6 13. Ne2 Qd5 14. Nc3 Qxe5 15. Bxe5 O-O 16. Bd3 h5 17. Ne2 Nd5 18. Bxg7 Kxg7 19. c4 Nf6 20. Nf4 Rd8 21. d5 cxd5 22. cxd5 Nxd5 23. Bc4 e6 24. Nxh5+ Kf8 25. Nf6 Ke7 26. Nxg4 b5 27. Bxd5 exd5 28. Rhe1+ Kf8 29. Ne5 Bf5 30. Kd2 f6 31. Nc6 Rd6 32. Nd4 Bd7 33. Rc1 Kg7 34. Re7+ Kg6 35. Rc7 Rd8 36. g4 Kh6 37. f4 Kg6 38. h5+ Kh6 39. Rcxd7 R6xd7 40. Nf5# { Black checkmated } 1-0
Traceback (most recent call last):
  **File "process_data.py", line 174, in <module>
    main()
  File "process_data.py", line 170, in main
    gen_board_pair_data(datafile, 'training_data')
  File "process_data.py", line 76, in gen_board_pair_data
    while not node.is_end():
AttributeError: 'Game' object has no attribute 'is_end**

my branch is here 
https://github.com/johndpope/AdversarialChess

**Comment by johndpope** [comment]
note - I'm using the tal.png and same ficsgamesdb_2015_standard2000_nomovetimes_1429742.pgn file

**Comment by johndpope** [comment]
fixed by not using conda and upgrading python chess https://github.com/niklasf/python-chess/issues/88
