### ISSUE TITLE
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

### ISSUE THREAD

**Issue by johndpope** [2014mchidamb/AdversarialChess#4]
`Traceback (most recent call last):
  File "train_model.py", line 15, in <module>
    magikarp.train()
  File "/Users/johndpope/Documents/tensorFlowWorkspace/AdversarialChess/model.py", line 215, in train
    self.create_model()
  File "/Users/johndpope/Documents/tensorFlowWorkspace/AdversarialChess/model.py", line 197, in create_model
    self.create_dis_model()
  File "/Users/johndpope/Documents/tensorFlowWorkspace/AdversarialChess/model.py", line 187, in create_dis_model
    self.d_pred_real = self.d_predict(tf.concat(1, [self.person_board_1, self.person_board_2]), self.p_keep)
  File "/Users/johndpope/miniconda2/envs/tensorflow-p2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1029, in concat
    dtype=dtypes.int32).get_shape(
  File "/Users/johndpope/miniconda2/envs/tensorflow-p2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 639, in convert_to_tensor
    as_ref=False)
  File "/Users/johndpope/miniconda2/envs/tensorflow-p2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 704, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/johndpope/miniconda2/envs/tensorflow-p2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/johndpope/miniconda2/envs/tensorflow-p2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/johndpope/miniconda2/envs/tensorflow-p2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 370, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Users/johndpope/miniconda2/envs/tensorflow-p2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.`

was there a specific tensorflow version you used?

**Comment by johndpope** [comment]
fixed.
https://github.com/tensorflow/tensorflow/issues/7031

-		self.d_pred_real = self.d_predict(tf.concat(1, [self.person_board_1, self.person_board_2]), self.p_keep)
-		self.d_pred_fake = self.d_predict(tf.concat(1, [self.person_board_1, self.gen_board]), self.p_keep)
+		self.d_pred_real = self.d_predict(tf.concat([self.person_board_1, self.person_board_2],1), self.p_keep)
+		self.d_pred_fake = self.d_predict(tf.concat([self.person_board_1, self.gen_board],1), self.p_keep)
